version: '3'
services:
  db:
    image: mysql:5.6
    container_name: night-life.db
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

volumes:
  db-data:
