version: "3"
services:
  db:
    image: mysql:5.6
    container_name: night-life.db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

volumes:
  db-data:
