# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
