# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190304_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('cookie', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='video',
            name='folder',
        ),
        migrations.AlterField(
            model_name='video',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='VideoFolder',
        ),
    ]
